name: FalixNodes AFK-Killer
on:
  schedule:
    - cron: '*/20 * * * *' # Запуск каждые 20 минут автоматически
  workflow_dispatch: # Позволяет запустить вручную кнопкой

jobs:
  bypass:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install undetected-chromedriver selenium requests

      - name: Run AFK Killer
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SERVER_ID: ${{ secrets.SERVER_ID }}
        run: python bot.py

      # ЭТОТ БЛОК СОХРАНИТ СКРИНШОТ ПРИ ОШИБКЕ
      - name: Upload Debug Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: "*.png"
          retention-days: 1
